-- Phase 23: Seed CMS blocks for 12 Guided Request Steps and Auth Method Toggles
-- Auth methods: Email authentication is enabled by default ('true'); Phone authentication is disabled by default ('false').
INSERT INTO content_blocks (key, title_en, body_en, status)
VALUES
  ('auth.email_enabled', 'Email Authentication & OTP', 'true', 'published'),
  ('auth.phone_enabled', 'Phone Authentication & OTP', 'false', 'published'),
  ('request.step1.eyebrow', 'Step 1 • Care Recipient', 'Step 1 • Care Recipient', 'published'),
  ('request.step1.title', 'Who needs care support at the hospital?', 'Who needs care support at the hospital?', 'published'),
  ('request.step1.desc', 'Care Recipient Description', 'We tailor mobility equipment, escort dialect, and care rendezvous around the patient.', 'published'),
  ('request.step2.eyebrow', 'Step 2 • Care Services', 'Step 2 • Care Services', 'published'),
  ('request.step2.title', 'Which support services do you need?', 'Which support services do you need?', 'published'),
  ('request.step2.desc', 'Care Services Description', 'Select one or more services. All options include an on-ground care companion escort.', 'published'),
  ('request.step3.eyebrow', 'Step 3 • Hospital Selection', 'Step 3 • Hospital Selection', 'published'),
  ('request.step3.title', 'Which hospital will you be visiting?', 'Which hospital will you be visiting?', 'published'),
  ('request.step3.desc', 'Hospital Selection Description', 'Our care companions have verified security badges and designated rendezvous desks at these partner hospitals.', 'published'),
  ('request.step4.eyebrow', 'Step 4 • Visit Purpose', 'Step 4 • Visit Purpose', 'published'),
  ('request.step4.title', 'What is the purpose of this hospital visit?', 'What is the purpose of this hospital visit?', 'published'),
  ('request.step4.desc', 'Visit Purpose Description', 'Help our companion prepare appropriate files, token queues, and wheelchair support.', 'published'),
  ('request.step5.eyebrow', 'Step 5 • Schedule & Timing', 'Step 5 • Schedule & Timing', 'published'),
  ('request.step5.title', 'When do you need companion accompaniment?', 'When do you need companion accompaniment?', 'published'),
  ('request.step5.desc', 'Schedule Description', 'Select your scheduled consultation or hospital admission date and arrival slot.', 'published'),
  ('request.step6.eyebrow', 'Step 6 • Transit & Pickup', 'Step 6 • Transit & Pickup', 'published'),
  ('request.step6.title', 'Do you require home transit or doorstep pickup?', 'Do you require home transit or doorstep pickup?', 'published'),
  ('request.step6.desc', 'Transit Description', 'We arrange sanitized transit with wheelchair boarding assistance from your residence to the hospital.', 'published'),
  ('request.step7.eyebrow', 'Step 7 • Journey Updates', 'Step 7 • Journey Updates', 'published'),
  ('request.step7.title', 'Who should receive live journey updates?', 'Who should receive live journey updates?', 'published'),
  ('request.step7.desc', 'Journey Updates Description', 'We send timestamped milestone notifications (Arrival, OPD Doctor Intake, Pharmacy Dossier) via SMS & WhatsApp.', 'published'),
  ('request.step8.eyebrow', 'Step 8 • Special Directives', 'Step 8 • Special Directives', 'published'),
  ('request.step8.title', 'Any mobility assistance or special directives?', 'Any mobility assistance or special directives?', 'published'),
  ('request.step8.desc', 'Special Directives Description', 'Tell us if the patient requires wheelchair ramp access, Telugu/Hindi speaking escort, or lift assistance.', 'published'),
  ('request.step9.eyebrow', 'Step 9 • Review Details', 'Step 9 • Review Details', 'published'),
  ('request.step9.title', 'Review your journey details', 'Review your journey details', 'published'),
  ('request.step9.desc', 'Review Description', 'Please confirm all details before submitting. You can click Edit on any section to make changes.', 'published'),
  ('request.step10.eyebrow', 'Step 10 • Verification', 'Step 10 • Verification', 'published'),
  ('request.step10.title', 'Verify your account', 'Verify your account', 'published'),
  ('request.step10.desc', 'Verification Description', 'We verify your identity to dispatch live updates and doctor dossiers.', 'published'),
  ('request.step11.title', 'Securing Care Request...', 'Securing Care Request...', 'published'),
  ('request.step11.desc', 'Submitting Description', 'Submitting your details securely to our operations hospital coordination desk.', 'published'),
  ('request.step12.title', 'Care Request Submitted!', 'Care Request Submitted!', 'published'),
  ('request.step12.desc', 'Success Description', 'Our operations coordinator is reviewing hospital desk availability and assigning a dedicated companion escort.', 'published')
ON CONFLICT (key) DO UPDATE
  SET title_en = EXCLUDED.title_en,
      body_en = EXCLUDED.body_en,
      status = 'published',
      updated_at = now();
