// Local-dev seed ONLY. Never run against staging/production.
// Creates an ops head login + sample published CMS content.
import 'dotenv/config';
import pg from 'pg';
import { hashPassword } from '../src/modules/auth/password.js';

const url = process.env.DATABASE_URL;
if (!url) {
  console.error('DATABASE_URL is required.');
  process.exit(1);
}

const client = new pg.Client({ connectionString: url });
await client.connect();
try {
  const email = 'ops@aayuyukthi.local';
  const hash = await hashPassword('ChangeMe123!');
  const { rows } = await client.query(
    `INSERT INTO users (email, password_hash, full_name, status) VALUES ($1,$2,'Local Ops Head','active')
     ON CONFLICT DO NOTHING RETURNING id`,
    [email, hash],
  );
  let userId = rows[0]?.id;
  if (!userId) {
    userId = (await client.query('SELECT id FROM users WHERE lower(email)=lower($1)', [email])).rows[0].id;
  }
  for (const role of ['operations_head', 'content_manager']) {
    await client.query('INSERT INTO user_roles (user_id, role, assigned_by) VALUES ($1,$2,$1) ON CONFLICT DO NOTHING', [userId, role]);
  }

  const servicesSeed = [
    {
      slug: 'appointment-coordination',
      title_en: 'Appointment Coordination',
      category: 'outpatient',
      subtitle_en: 'From ₹499 / Visit',
      icon: 'calendar_month',
      description_en: 'Doctor slot reservations, re-confirmations, medical summary preparations, and diagnostic timing alignment to minimize hospital lobby waiting times.',
      benefits_en: ['Direct booking with specialists', 'Zero waiting room friction', 'Document readiness review'],
      sort_order: 1,
    },
    {
      slug: 'hospital-visit-accompaniment',
      title_en: 'Hospital Visit Accompaniment',
      category: 'outpatient',
      subtitle_en: 'Half: ₹1,299 • Full: ₹2,199',
      icon: 'accessible_forward',
      description_en: 'An empathetic dedicated care coordinator stays physically beside you or your elderly family member through registration, OPD queues, doctor consults, and pharmacy collection.',
      benefits_en: ['Verified compassionate companion', 'Wheelchair assistance available', 'Real-time SMS family updates'],
      sort_order: 2,
    },
    {
      slug: 'pickup-drop',
      title_en: 'Pickup & Drop Support',
      category: 'logistics',
      subtitle_en: 'From ₹899 / Trip',
      icon: 'directions_car',
      description_en: 'Safe, doorstep chauffeured transit with companion assistance into and out of vehicles. Foldable wheelchair accommodation available upon request.',
      benefits_en: ['Sanitized door-to-door transit', 'Punctual hospital arrival', 'Trained patient-assistance drivers'],
      sort_order: 3,
    },
    {
      slug: 'hospital-process-billing',
      title_en: 'Hospital Process & Billing Assistance',
      category: 'administrative',
      subtitle_en: 'From ₹799 / Consultation',
      icon: 'description',
      description_en: 'TPA desk coordination, health insurance pre-authorizations, bill settlements, and discharge summary compilations made simple.',
      benefits_en: ['Cashless claim desk navigation', 'Accelerated discharge clearance', 'Itemized invoice audit'],
      sort_order: 4,
    },
    {
      slug: 'treatment-diagnostic-support',
      title_en: 'Treatment & Diagnostic Visit Support',
      category: 'outpatient',
      subtitle_en: 'From ₹1,199 / Session',
      icon: 'biotech',
      description_en: 'Comprehensive support for specialized imaging (MRI/CT), dialysis sessions, chemo day-care, and routine periodic pathology tests.',
      benefits_en: ['Fast-track prep adherence', 'Dedicated bay accompaniment', 'Safe return handover'],
      sort_order: 5,
    },
    {
      slug: 'recurring-care-coordination',
      title_en: 'Recurring Care Coordination',
      category: 'recurring',
      subtitle_en: 'From ₹2,999 / Month',
      icon: 'volunteer_activism',
      description_en: 'Monthly ongoing plans for senior citizens and chronic care patients needing regular follow-ups, diagnostic monitoring, and medicine deliveries.',
      benefits_en: ['Dedicated primary care manager', 'Automatic appointment cadence', 'Comprehensive monthly health digest'],
      sort_order: 6,
    },
  ];

  for (const s of servicesSeed) {
    await client.query(
      `INSERT INTO services (slug, title_en, description_en, benefits_en, subtitle_en, icon, category, sort_order, status, is_visible, created_by, updated_by)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'published', true, $9, $9)
       ON CONFLICT (slug) DO UPDATE SET
         title_en = EXCLUDED.title_en,
         description_en = EXCLUDED.description_en,
         benefits_en = EXCLUDED.benefits_en,
         subtitle_en = EXCLUDED.subtitle_en,
         icon = EXCLUDED.icon,
         category = EXCLUDED.category,
         sort_order = EXCLUDED.sort_order,
         status = 'published',
         is_visible = true,
         updated_by = EXCLUDED.updated_by`,
      [s.slug, s.title_en, s.description_en, s.benefits_en, s.subtitle_en, s.icon, s.category, s.sort_order, userId],
    );
  }

  const hospitalsSeed = [
    {
      slug: 'varma-hospitals',
      name_en: 'Varma Hospitals',
      city: 'Bhimavaram',
      state: 'Andhra Pradesh',
      address_en: 'Main Road, Bhimavaram, West Godavari, Andhra Pradesh 534201',
      description_en: 'Comprehensive multi-specialty healthcare center providing compassionate outpatient care, surgical interventions, and dedicated elderly diagnostics in Bhimavaram.',
      campus_highlight_en: 'Bhimavaram Active • 15m Lobby SLA',
      wait_info_en: 'Avg Coordinator Wait: 0 mins (Main Reception Porch)',
      features_en: ['Companion Escort', 'Wheelchair Logistics', 'OPD Navigation', 'Diagnostics Flow'],
    },
    {
      slug: 'imperial-hospitals',
      name_en: 'Imperial Hospitals',
      city: 'Bhimavaram',
      state: 'Andhra Pradesh',
      address_en: 'Bhimavaram Town, West Godavari, Andhra Pradesh 534201',
      description_en: 'Advanced clinical and surgical hospital equipped with modern intensive care units, round-the-clock emergency assistance, and rapid outpatient services.',
      campus_highlight_en: 'Bhimavaram Active • 15m Lobby SLA',
      wait_info_en: 'Avg Coordinator Wait: 0 mins (Gate 1 Lobby Desk)',
      features_en: ['Companion Escort', 'Wheelchair Logistics', 'Doctor Consult Escort', 'Pharmacy Support'],
    },
    {
      slug: 'akshara-speciality-hospitals',
      name_en: 'Akshara Speciality Hospitals',
      city: 'Bhimavaram',
      state: 'Andhra Pradesh',
      address_en: 'Bhimavaram, West Godavari, Andhra Pradesh 534202',
      description_en: 'Specialized healthcare hub offering cardiology, nephrology, orthopedics, and integrated diagnostic laboratories for senior citizens.',
      campus_highlight_en: 'Bhimavaram Active • 15m Lobby SLA',
      wait_info_en: 'Avg Coordinator Wait: 0 mins (Speciality Clinic Atrium)',
      features_en: ['Companion Escort', 'Wheelchair Support', 'TPA Desk Help', 'Diagnostics Escort'],
    },
    {
      slug: 'mithra-medicare-hospital',
      name_en: 'Mithra Medicare Hospital',
      city: 'Bhimavaram',
      state: 'Andhra Pradesh',
      address_en: 'Near Bus Stand Road, Bhimavaram, West Godavari, Andhra Pradesh 534201',
      description_en: 'Trusted community healthcare facility offering general medicine, pediatrics, geriatric evaluations, and health check packages.',
      campus_highlight_en: 'Bhimavaram Active • 15m Lobby SLA',
      wait_info_en: 'Avg Coordinator Wait: 0 mins (Front Entrance Meetup)',
      features_en: ['Companion Escort', 'Wheelchair Assistance', 'OPD Token Fast-track', 'Billing Desk Help'],
    },
    {
      slug: 'nallaparaju-venkata-raju-hospital',
      name_en: 'Nallaparaju Venkata Raju Hospital',
      city: 'Bhimavaram',
      state: 'Andhra Pradesh',
      address_en: 'Bhimavaram, West Godavari, Andhra Pradesh 534201',
      description_en: 'Established medical center providing comprehensive inpatient care, minor surgical procedures, and dedicated nursing care in the heart of Bhimavaram.',
      campus_highlight_en: 'Bhimavaram Active • 15m Lobby SLA',
      wait_info_en: 'Avg Coordinator Wait: 0 mins (Lobby Registration Desk)',
      features_en: ['Companion Escort', 'Transit Assistance', 'Elderly Mobility Care', 'Prescription Pickup'],
    },
    {
      slug: 'rajarshi-hospitals',
      name_en: 'Rajarshi Hospitals',
      city: 'Bhimavaram',
      state: 'Andhra Pradesh',
      address_en: 'Bhimavaram Town, West Godavari, Andhra Pradesh 534202',
      description_en: 'Multi-specialty hospital renowned for orthopedic surgery, trauma recovery, geriatric rehabilitation, and outpatient clinics.',
      campus_highlight_en: 'Bhimavaram Active • 15m Lobby SLA',
      wait_info_en: 'Avg Coordinator Wait: 0 mins (Main Hospital Porch)',
      features_en: ['Companion Escort', 'Wheelchair Transfer', 'Doctor Consult Navigation', 'Discharge Assistance'],
    },
    {
      slug: 'bhimavaram-hospitals',
      name_en: 'Bhimavaram Hospitals',
      city: 'Bhimavaram',
      state: 'Andhra Pradesh',
      address_en: 'Bhimavaram, West Godavari, Andhra Pradesh 534201',
      description_en: 'Prominent regional multi-specialty institute serving Bhimavaram and surrounding areas with modern operating theaters and multi-specialty clinics.',
      campus_highlight_en: 'Bhimavaram Active • 15m Lobby SLA',
      wait_info_en: 'Avg Coordinator Wait: 0 mins (Central OPD Concourse)',
      features_en: ['Companion Escort', 'Wheelchair Logistics', 'OPD Navigation', 'Lab Diagnostics Escort'],
    },
    {
      slug: 'teja-super-speciality-hospital',
      name_en: 'Teja Super Speciality Hospital',
      city: 'Bhimavaram',
      state: 'Andhra Pradesh',
      address_en: 'PP Road, Bhimavaram, West Godavari, Andhra Pradesh 534201',
      description_en: 'Super-specialty center offering advanced neurology, gastroenterology, laparoscopic surgeries, and round-the-clock emergency trauma care.',
      campus_highlight_en: 'Bhimavaram Active • 15m Lobby SLA',
      wait_info_en: 'Avg Coordinator Wait: 0 mins (Super Speciality Reception)',
      features_en: ['Companion Escort', 'Wheelchair Logistics', 'TPA Pre-Clearing', 'Pharmacy Fulfillment'],
    },
    {
      slug: 'vh-care-multi-speciality-hospital',
      name_en: 'VH Care Multi-speciality Hospital',
      city: 'Bhimavaram',
      state: 'Andhra Pradesh',
      address_en: 'Bhimavaram, West Godavari, Andhra Pradesh 534203',
      description_en: 'Modern multi-specialty hospital focused on patient comfort, minimally invasive procedures, diagnostic ultrasound, and chronic disease clinics.',
      campus_highlight_en: 'Bhimavaram Active • 15m Lobby SLA',
      wait_info_en: 'Avg Coordinator Wait: 0 mins (Ground Floor Reception)',
      features_en: ['Companion Escort', 'Wheelchair Logistics', 'OPD Token Assistance', 'Medicine Collection'],
    },
    {
      slug: 'sri-venkateswara-hospitals',
      name_en: 'Sri Venkateswara Hospitals',
      city: 'Bhimavaram',
      state: 'Andhra Pradesh',
      address_en: 'Bhimavaram, West Godavari, Andhra Pradesh 534202',
      description_en: 'Family healthcare center delivering compassionate internal medicine, maternal health, geriatric consultations, and routine medical treatments.',
      campus_highlight_en: 'Bhimavaram Active • 15m Lobby SLA',
      wait_info_en: 'Avg Coordinator Wait: 0 mins (Main Admission Gate)',
      features_en: ['Companion Escort', 'Mobility Assistance', 'Doctor Consultation Escort', 'Billing Support'],
    },
    {
      slug: 'sri-lakshmi-hospitals',
      name_en: 'Sri Lakshmi Hospitals',
      city: 'Bhimavaram',
      state: 'Andhra Pradesh',
      address_en: 'Bhimavaram, West Godavari, Andhra Pradesh 534201',
      description_en: 'Reputed local hospital providing specialized gynecological, surgical, orthopedic, and general physician outpatient consultations.',
      campus_highlight_en: 'Bhimavaram Active • 15m Lobby SLA',
      wait_info_en: 'Avg Coordinator Wait: 0 mins (Outpatient Lounge)',
      features_en: ['Companion Escort', 'Wheelchair Logistics', 'Diagnostic Escort', 'Patient Advocacy'],
    },
    {
      slug: 'vinayaka-hospital',
      name_en: 'Vinayaka Hospital',
      city: 'Bhimavaram',
      state: 'Andhra Pradesh',
      address_en: 'Bhimavaram, West Godavari, Andhra Pradesh 534201',
      description_en: 'Patient-centric hospital providing high-standard medical treatment, pediatric care, general surgical procedures, and preventive checkups.',
      campus_highlight_en: 'Bhimavaram Active • 15m Lobby SLA',
      wait_info_en: 'Avg Coordinator Wait: 0 mins (Porch Registration Area)',
      features_en: ['Companion Escort', 'Queue Fast-track', 'Wheelchair Support', 'Prescription Handling'],
    },
    {
      slug: 'sai-indian-hospitals',
      name_en: 'Sai Indian Hospitals',
      city: 'Bhimavaram',
      state: 'Andhra Pradesh',
      address_en: 'Bhimavaram, West Godavari, Andhra Pradesh 534202',
      description_en: 'Comprehensive surgical and medical facility offering inpatient wards, day-care services, and specialized outpatient clinics in Bhimavaram.',
      campus_highlight_en: 'Bhimavaram Active • 15m Lobby SLA',
      wait_info_en: 'Avg Coordinator Wait: 0 mins (Main Lobby Desk)',
      features_en: ['Companion Escort', 'Wheelchair Logistics', 'Transit Transfer', 'Discharge Coordination'],
    },
    {
      slug: 'neeladri-hospitals',
      name_en: 'Neeladri Hospitals',
      city: 'Bhimavaram',
      state: 'Andhra Pradesh',
      address_en: 'Bhimavaram Town, West Godavari, Andhra Pradesh 534201',
      description_en: 'Dedicated multi-specialty hospital providing trusted medical care across cardiology, diabetology, pulmonology, and elder wellness programs.',
      campus_highlight_en: 'Bhimavaram Active • 15m Lobby SLA',
      wait_info_en: 'Avg Coordinator Wait: 0 mins (Front Porch Reception)',
      features_en: ['Companion Escort', 'Wheelchair Logistics', 'OPD Guidance', 'Diagnostic Test Flow'],
    },
    {
      slug: 'abhiram-orthopaedic-hospital',
      name_en: 'Abhiram Orthopaedic Hospital',
      city: 'Bhimavaram',
      state: 'Andhra Pradesh',
      address_en: 'Bhimavaram, West Godavari, Andhra Pradesh 534202',
      description_en: 'Premier orthopedic and joint care hospital specializing in knee and hip replacement, trauma surgery, fracture care, and rehabilitation therapies.',
      campus_highlight_en: 'Bhimavaram Active • 15m Lobby SLA',
      wait_info_en: 'Avg Coordinator Wait: 0 mins (Orthopedic Clinic Porch)',
      features_en: ['Companion Escort', 'Wheelchair Transit Assistance', 'X-Ray & MRI Escort', 'Rehab Navigation'],
    },
    {
      slug: 'maxivision-super-speciality-eye-hospitals',
      name_en: 'Maxivision Super Speciality Eye Hospitals',
      city: 'Bhimavaram',
      state: 'Andhra Pradesh',
      address_en: 'Bhimavaram, West Godavari, Andhra Pradesh 534201',
      description_en: 'Leading ophthalmic hospital providing world-class cataract surgeries, retina interventions, glaucoma care, and vision correction treatments.',
      campus_highlight_en: 'Bhimavaram Active • 15m Lobby SLA',
      wait_info_en: 'Avg Coordinator Wait: 0 mins (Eye Care Clinic Lobby)',
      features_en: ['Companion Escort', 'Dilation & Test Escort', 'Senior Citizen Walking Support', 'Drop Admin Help'],
    },
  ];

  for (const h of hospitalsSeed) {
    await client.query(
      `INSERT INTO hospitals (slug, name_en, description_en, city, state, address_en, campus_highlight_en, wait_info_en, features_en, status, is_visible, created_by, updated_by)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'published', true, $10, $10)
       ON CONFLICT (slug) DO UPDATE SET
         name_en = EXCLUDED.name_en,
         description_en = EXCLUDED.description_en,
         city = EXCLUDED.city,
         state = EXCLUDED.state,
         address_en = EXCLUDED.address_en,
         campus_highlight_en = EXCLUDED.campus_highlight_en,
         wait_info_en = EXCLUDED.wait_info_en,
         features_en = EXCLUDED.features_en,
         status = 'published',
         is_visible = true,
         updated_by = EXCLUDED.updated_by`,
      [h.slug, h.name_en, h.description_en, h.city, h.state, h.address_en, h.campus_highlight_en, h.wait_info_en, h.features_en, userId],
    );
  }

  await client.query(
    `INSERT INTO faqs (question_en, answer_en, category, is_published, created_by)
     VALUES ('What does AayuYukthi do?','We coordinate hospital journeys: appointments, pickup, and updates.','general',true,$1)
     ON CONFLICT DO NOTHING`,
    [userId],
  );
  for (const [key, title, body, icon] of [
    ['about.story', 'Our story', 'AayuYukthi began with a simple observation: hospital visits are hard to navigate alone. We coordinate the journey so families can focus on care.', null],
    ['about.mission', 'Our mission', 'Reliable, human support for every hospital journey.', null],
    ['about.vision', 'Our vision', 'A future where no one faces a hospital visit without support.', null],
    ['about.values', 'Our values', 'Trust, care, reliability, and accessibility in everything we do.', null],
    ['about.hero.badge', 'Founding Purpose', 'OUR FOUNDING PURPOSE • HUMAN-CENTERED ADVOCACY', 'verified'],
    ['about.hero.title', 'Hero Title', 'Making hospital journeys easier, dignified, and stress-free.', null],
    ['about.hero.description', 'Hero Description', 'AayuYukthi was born from a fundamental realization: navigating premier hospitals when unwell or caring for elderly loved ones is emotionally exhausting. We bridge the gap between home doorstep and clinical care with dedicated, empathetic companions.', null],
    ['about.metric1.value', 'Metric 1 Value', '35,000+', null],
    ['about.metric1.label', 'Metric 1 Label', 'Assisted Hours', null],
    ['about.metric1.sub', 'Metric 1 Subtitle', 'Uninterrupted bedside & corridor support', null],
    ['about.metric2.value', 'Metric 2 Value', '42+', null],
    ['about.metric2.label', 'Metric 2 Label', 'Partner Hospital Hubs', null],
    ['about.metric2.sub', 'Metric 2 Subtitle', 'Accredited private & tertiary campuses', null],
    ['about.metric3.value', 'Metric 3 Value', '99.2%', null],
    ['about.metric3.label', 'Metric 3 Label', 'Punctual Escort SLA', null],
    ['about.metric3.sub', 'Metric 3 Subtitle', '15-minute lobby check-in reliability', null],
    ['about.metric4.value', 'Metric 4 Value', '4.9/5', null],
    ['about.metric4.label', 'Metric 4 Label', 'Caregiver Satisfaction', null],
    ['about.metric4.sub', 'Metric 4 Subtitle', 'Verified post-consult family reviews', null],
    ['about.story.badge', 'Story Badge', 'Origin Narrative', null],
    ['about.story.title', 'Story Title', 'The Unseen Burden of Hospital Corridors', null],
    ['about.story.quote', 'Founder Quote', '“Hospitals heal illness, but navigating them should not create fresh illness. We envisioned an empathetic buffer—a calm, capable companion standing between vulnerable patients and operational friction.”', 'format_quote'],
    ['about.story.quote_author', 'Quote Author', 'Ananya V. Deshmukh', null],
    ['about.story.quote_role', 'Quote Author Role', 'Founder & Care Operations Director', null],
    ['about.val1.title', 'Value 1 Title', '1. Unconditional Care', 'favorite'],
    ['about.val1.body', 'Value 1 Description', 'Empathy is present in every touchpoint—holding hands through noisy corridors, offering calm words during test delays, and treating seniors with familial reverence.', null],
    ['about.val2.title', 'Value 2 Title', '2. Absolute Trust', 'verified_user'],
    ['about.val2.body', 'Value 2 Description', '100% background-verified, non-commissioned advocates. Our loyalties remain exclusively with the patient, never swayed by third-party agendas.', null],
    ['about.val3.title', 'Value 3 Title', '3. Punctual Reliability', 'alarm_on'],
    ['about.val3.body', 'Value 3 Description', 'Strict 15-minute lobby arrival guarantee before appointment slots. We value the physical energy of tired patients and never let them wait unattended.', null],
    ['about.val4.title', 'Value 4 Title', '4. Dignified Respect', 'accessibility_new'],
    ['about.val4.body', 'Value 4 Description', 'Empowering patient autonomy, preserving personal privacy during doctor examinations, and never treating elderly individuals like helpless dependents.', null],
    ['about.val5.title', 'Value 5 Title', '5. Universal Accessibility', 'translate'],
    ['about.val5.body', 'Value 5 Description', 'Native multilingual companion matching across English, Telugu, Hindi, Kannada, and Tamil to ensure total comfort without communication gaps.', null],
    ['about.val6.title', 'Value 6 Title', '6. Strict Responsibility', 'receipt_long'],
    ['about.val6.body', 'Value 6 Description', 'Clear, transparent hourly pricing. Absolute zero kickbacks or referral fees from laboratories, diagnostic centres, or pharmaceutical shops.', null],
    ['about.cta.badge', 'CTA Badge', 'WE ARE STANDING BY 7 DAYS A WEEK', 'support_agent'],
    ['about.cta.title', 'CTA Title', 'Experience peaceful healthcare accompaniment.', null],
    ['about.cta.body', 'CTA Description', 'Book a dedicated care companion for your parents or loved ones. Same-day urgent and scheduled outpatient slots available across all partner hubs.', null],
    ['about.cta.disclaimer', 'CTA Disclaimer', 'Mandatory Non-Clinical Notice: AayuYukthi provides care coordination, logistical assistance, and patient advocacy. We are not a hospital, clinical medical provider, or emergency service. All medical choices, diagnosis, and treatment protocols remain strictly between licensed doctors and the patient.', null],
    // Profile Page CMS Blocks
    ['profile.header.badge', 'Account Badge', 'Family Caregiver Account Admin', 'verified_user'],
    ['profile.header.network', 'Care Network Hub', 'Apollo Bannerghatta & Manipal Old Airport Road Network', 'domain'],
    ['profile.health.status', 'Account Health Status', 'Active & Insured', 'check_circle'],
    ['profile.stats.punctuality', 'Punctuality SLA Score', '100%', 'avg_pace'],
    ['profile.stats.billing', 'Billing Balance', '₹0 Pending', 'account_balance_wallet'],
    ['profile.banner.policy', 'Zero Advance Policy Title', 'Zero Advance Deposit Policy', 'handshake'],
    ['profile.banner.policy_sub', 'Policy Description', 'All companion escorts operate on "Pay After Service Handshake". Charges are triggered only after patient reaches home safely.', null],
    ['profile.emergency.notice', 'Escalation Notice', 'This contact receives automated WhatsApp milestones, real-time GPS transit links, and can authorize emergency clinical escort directives if you cannot be reached within 15 minutes of doctor consultations.', 'info'],
    ['profile.coordinator.name', 'Designated Coordinator Name', 'Pooja Sharma', 'verified'],
    ['profile.coordinator.role', 'Coordinator Specialization', 'Apollo & Manipal Specialist', null],
    ['profile.coordinator.rating', 'Coordinator Rating & Escorts', '4.98 Rating • 180+ Escorts', null],
    ['profile.coordinator.bio', 'Coordinator Bio', 'Pooja is assigned to all family appointments across Bengaluru East. She oversees pre-transit checkups and hospital queue clearances.', null],
    ['profile.coordinator.phone', 'Coordinator Helpline Phone', '1800-AAYU-CARE', 'call'],
    ['profile.trust.title', 'Trust Protocol Title', 'AayuYukthi Trust Protocol', 'verified_user'],
    ['profile.trust.body', 'Trust Protocol Description', 'Your family account complies with ISO 27001 medical transit guidelines. All transit escorts carry physical ID badges with cryptographic QR links verified directly by hospital entrance security desks.', null],
    ['profile.privacy.disclaimer', 'Data Governance', 'Aligned with India Digital Information Security in Healthcare Act (DISHA) & HIPAA.', 'privacy_tip'],
    ['home.disclaimer', '', 'AayuYukthi provides care coordination & accompaniment. We are not a hospital or emergency service.', null],
    ['home.eyebrow', '', 'CARE THAT COMES CLOSER', null],
    ['home.hero.title', '', 'Support through every hospital journey.', null],
    ['home.hero.description', '', 'AayuYukthi helps you coordinate hospital visits, appointments, and care-related logistics with ease, dignity, and zero stress for your loved ones.', null],
    ['home.hero.primary_label', '', 'Request Care', null],
    ['home.hero.primary_url', '', '/request-care', null],
    ['home.hero.secondary_label', '', 'Explore Services', null],
    ['home.hero.secondary_url', '', '/services', null],
    ['home.journey.label', '', 'Journey Steps', null],
    ['home.trust.1', 'Care Coordination', 'Dedicated personal companions for entire outpatient or diagnostic visits.', 'person_pin_circle'],
    ['home.trust.2', 'Reliable Support', 'Thoroughly vetted, background-verified, and empathetic coordinators.', 'verified_user'],
    ['home.trust.3', 'Hospital Navigation', 'Fast-track queues, paperwork handling, pharmacy pick-up, and billing support.', 'local_hospital'],
    ['home.trust.4', 'Family-Centered Care', 'Real-time status notifications sent directly to family members.', 'family_restroom'],
    ['home.how.eyebrow', '', 'Effortless Workflow', null],
    ['home.how.title', '', 'How AayuYukthi works', null],
    ['home.how.sub', '', 'A simple journey to peaceful, dignified medical visits.', null],
    ['home.how.1', 'Tell us what you need', 'Share appointment details, hospital choice, and assistance level.', 'chat'],
    ['home.how.2', 'Select recipient & transit', 'Specify for self, parents, or relatives. Add wheelchair transit.', 'accessible'],
    ['home.how.3', 'Coordinator assigned', 'A certified companion confirms logistics and meets you at the entrance.', 'badge'],
    ['home.how.4', 'Real-time family updates', 'Live milestone tracking: arrival, consult, prescriptions, next steps.', 'notifications_active'],
    ['home.how.5', 'Journey completed', 'Safe drop-off, organized prescriptions, and full visit handover.', 'check_circle'],
    ['home.services.eyebrow', '', 'Empathetic Assistance', null],
    ['home.services.title', '', 'Support when you need it.', null],
    ['home.services.sub', '', 'Flexible packages engineered around patient comfort and family relief.', null],
    ['home.hospitals.eyebrow', '', 'Partner Ecosystem', null],
    ['home.hospitals.title', '', 'Hospitals we support', null],
    ['home.hospitals.sub', '', 'Seamless on-ground coordination across accredited medical centers.', null],
    ['home.pillars.eyebrow', '', 'The Human Touch', null],
    ['home.pillars.title', '', 'Why Families Choose AayuYukthi', null],
    ['home.pillars.sub', '', 'We take away the logistical burden so you can focus on your family.', null],
    ['home.pillars.1', 'Zero Visit Anxiety', 'Navigating hospital towers, billing counters, and medicine lines is handled by trained staff.', 'psychology_alt'],
    ['home.pillars.2', 'Empathetic Caregivers', 'Companions chosen for emotional intelligence, offering bedside comfort and dignity.', 'volunteer_activism'],
    ['home.pillars.3', 'Family Visibility', 'Timely updates at every milestone, wherever in the world you are.', 'devices'],
    ['home.pillars.4', 'Transparent Pricing', 'Clear packages with zero surprise fees. Know upfront what assistance includes.', 'price_check'],
    ['home.testimonials.eyebrow', '', 'Real Stories', null],
    ['home.testimonials.title', '', 'Peace of mind for families everywhere', null],
    ['home.faq.eyebrow', '', 'Got Questions?', null],
    ['home.faq.title', '', 'Frequently Asked Questions', null],
    ['home.cta.eyebrow', '', 'Start Your Journey', null],
    ['home.cta.title', '', 'Need support with your next hospital visit?', null],
    ['home.cta.body', '', 'Tell us what you need and let AayuYukthi coordinate your journey from doorstep to discharge.', null],
    ['home.cta.primary_label', '', 'Request Care Now', null],
    ['home.cta.primary_url', '', '/request-care', null],
    ['home.cta.secondary_label', '', 'Contact Us', null],
    ['home.cta.secondary_url', '', '/contact', null],
    // Services Page CMS Blocks
    ['services.hero.eyebrow', '', 'Our Care Offerings', null],
    ['services.hero.badge', '', '100% Verified Companions across Bengaluru & Hyderabad', 'verified'],
    ['services.hero.title', '', 'Support designed around your hospital journey.', null],
    ['services.hero.body', '', 'Thoughtfully coordinated on-ground assistance, logistics, and compassionate accompaniment across every stage of outpatient and hospital care.', null],
    ['services.hero.bento_title', 'Zero Wait In Lobby', 'Coordinators arrive 20 mins early', 'health_and_safety'],
    ['services.hero.bento_coverage', 'Active Coverage', '42+ Hospitals', null],
    ['services.pillar.1', 'Background-Verified Companions', 'Every companion undergoes thorough background verification, criminal record checks, behavioral empathy screening, and geriatric emergency first-response training.', 'verified_user'],
    ['services.pillar.2', 'Live WhatsApp & SMS Milestones', 'Family members living in different cities or offices receive real-time timestamped status updates: "Arrived at Hospital", "With Doctor", "Blood Drawn", and "Prescriptions Secured".', 'notifications_active'],
    ['services.pillar.3', 'Non-Clinical & Strictly Neutral', 'We do not accept commissions from labs or recommend specific surgical treatments. Our role is strictly neutral care coordination, advocacy, transit ease, and patient peace of mind.', 'balance'],
    ['services.inquiry.title', '', 'Have unique requirements or hospital scheduling questions?', null],
    ['services.inquiry.body', '', 'Speak directly with an AayuYukthi care counselor. We customize schedules, wheelchair logistics, multiday packages, and multilingual coordinator pairings in minutes.', null],
    // Hospitals Page CMS Blocks
    ['hospitals.hero.eyebrow', '', 'NETWORK ECOSYSTEM • ACCREDITED HUBS', null],
    ['hospitals.hero.title', '', 'Find hospitals supported by AayuYukthi.', null],
    ['hospitals.hero.body', '', 'Explore premier tertiary and specialty healthcare centers across Bengaluru, Hyderabad, Delhi NCR, and Mumbai where our verified companions provide on-ground coordination and navigational relief.', null],
    ['hospitals.hero.pill_1', '', '100% Verified Multi-Wing Campus Coverage', 'verified'],
    ['hospitals.hero.pill_2', '', 'Care coordination & logistics service — independent of hospital administration', 'info'],
    ['hospitals.standards.eyebrow', '', 'How We Coordinate Inside Partner Campuses', null],
    ['hospitals.standards.title', '', 'Built for navigation ease inside complex hospitals.', null],
    ['hospitals.standards.body', '', 'AayuYukthi companions are trained in hospital layouts, patient advocacy, and eliminating bureaucratic wait times.', null],
    ['hospitals.standard.1', 'Familiar with Every Complex Wing & Block', 'From the shortest basement imaging elevators to secluded hydration chairs and calm waiting zones, our companions know the fastest routes across massive multi-tower campuses.', 'map'],
    ['hospitals.standard.2', 'Authorized Desk & TPA Pre-Clearing', 'We handle physical queueing for OPD tokens, insurance documentation hand-offs, and pharmacy collection while you or your loved one rest comfortably in shaded seating.', 'receipt_long'],
    ['hospitals.standard.3', 'Strict Non-Affiliated Patient Advocacy', 'We are completely independent advocates focused solely on the patient’s convenience, physical comfort, and peace of mind. No medical bias, no institutional commissions.', 'shield_person'],
    ['hospitals.custom.badge', '', 'Universal Coverage Guarantee', 'travel_explore'],
    ['hospitals.custom.title', '', 'Visiting a hospital or clinic not listed here?', null],
    ['hospitals.custom.body', '', 'AayuYukthi companions can escort you to ANY accredited hospital, standalone diagnostic lab, or specialty day-care center in our active metro coverage zones (Bengaluru, Hyderabad, NCR, Mumbai). Submit your center details and we will verify coordinator dispatch within 15 minutes.', null],
    ['hospitals.cta.title', '', 'Have an upcoming hospital consultation or admission?', 'support_agent'],
    ['hospitals.cta.body', '', 'Book a verified coordinator in under 2 minutes. We can meet you at your doorstep or directly at the hospital gate.', null],
    // Customer Auth Page CMS Blocks (Login, Signup, OTP Verification)
    ['auth.login.badge', '', 'AayuYukthi Family Access • Secure Care Portal', 'verified_user'],
    ['auth.login.title', '', 'Your family’s trusted companion through every hospital visit.', null],
    ['auth.login.description', '', 'Access your active care requests, review hospital visit milestones in real time, and coordinate dedicated support for your parents or loved ones.', null],
    ['auth.login.feature_1', 'Live Milestone Tracking', 'Real-time WhatsApp & portal updates during doctor consults, diagnostic scans, and medication dispensing.', 'timeline'],
    ['auth.login.feature_2', 'Verified Dedicated Companions', 'Police-vetted, empathetic coordinators offering bedside presence, wheelchair navigation, and patient advocacy.', 'badge'],
    ['auth.login.feature_3', 'Encrypted Health Dossiers', 'Instant digital access to clean discharge summaries, itemized bills, doctor prescriptions, and laboratory slips.', 'folder_special'],
    ['auth.login.testimonial_quote', '', '“Having AayuYukthi by my mother’s side at Apollo while I was in London gave our family complete peace of mind. Every prescription note was shared within minutes.”', null],
    ['auth.login.testimonial_author', '', '— Rohit M., Bengaluru', null],
    ['auth.login.testimonial_detail', '', 'Elder Care Service • Dec 2024', null],
    ['auth.signup.badge', '', 'Family Caregiver Network', 'verified_user'],
    ['auth.signup.title', '', 'You don\'t have to navigate hospital corridors alone.', null],
    ['auth.signup.description', '', 'Whether you are managing care from another city or balancing a demanding workday, AayuYukthi bridges the physical gap. We ensure your elderly parents are accompanied with dignity, gentleness, and clear real-time communication.', null],
    ['auth.signup.feature_1', 'Vetted Companions at Gate 1', 'Trained care coordinators meet parents directly at entry points with pre-arranged wheelchair transit.', 'handshake'],
    ['auth.signup.feature_2', 'Live Consultation Telemetry', 'Direct milestone updates as doctors prescribe medication, diagnostic tests commence, and vitals register.', 'notifications_active'],
    ['auth.signup.feature_3', 'Peace Across Distances', 'Full digital summaries, prescription pickups, and secure escort back into safe home transportation.', 'family_restroom'],
    ['auth.signup.social_proof_title', '', 'Trusted by 4,000+ Families', null],
    ['auth.signup.social_proof_cities', '', 'Bengaluru • Hyderabad • Delhi NCR • Mumbai', null],
    ['auth.signup.social_proof_quote', '', '“Being in London while Dad had his cardiology workups in Indiranagar was nerve-wracking until we set up AayuYukthi. The companion was attentive, punctual, and gentle.”', null],
    ['auth.otp.badge', '', 'Care Coordination', 'shield_with_heart'],
    ['auth.otp.title', '', 'Safeguarding your family’s healthcare journey.', null],
    ['auth.otp.description', '', 'We use two-factor verification to ensure all medical schedules, care recipient details, and live hospital updates remain strictly confidential.', null],
    ['auth.otp.feature_1', 'Instant Delivery', 'Passcode dispatched instantly to your registered email address via Resend.', 'mail'],
    ['auth.otp.feature_2', 'Dedicated Support Desk', 'Live care navigators available 7:00 AM – 9:00 PM IST daily.', 'headset_mic'],
    ['auth.otp.tip', '', 'Care coordinators will never ask for your 6-digit passcode over the phone, at hospital gates, or via unsecured links.', 'info'],
    ['auth.otp.coordinator_note', 'Assigned Care Coordinator: Rajesh Kumar', 'Apollo Spectra, Sector 8 • Awaiting your authorization for transit check-in', 'person'],
    ['auth.helpline.number', '', '1800-AAYU-CARE', null],
    ['auth.helpline.tel', '', 'tel:180022982273', null],
    ['auth.compliance.ssl', '', '256-bit SSL Protected', 'lock'],
    ['auth.compliance.privacy', '', 'ISO 27001 Certified Indian Healthcare Data Privacy', 'gavel'],
    // Customer Portal & Requests CMS Blocks
    ['customer.requests.eyebrow', '', 'Care Requests & Service Logs', 'format_list_bulleted'],
    ['customer.requests.title', '', 'My Care Requests', null],
    ['customer.requests.description', '', 'Track upcoming hospital visits, monitor live companion milestones, and access historical doctor notes and discharge dossiers.', null],
    ['customer.advisory.title', '', 'Need urgent modifications or companion adjustments?', 'verified_user'],
    ['customer.advisory.body', '', 'Changes are accommodated up to 4 hours prior to scheduled appointment with zero penalty.', null],
    ['customer.advisory.helpline', '', '1800-AAYU-CARE', 'call'],
    ['customer.advisory.tel', '', 'tel:180022982273', null],
    ['customer.metro.active', '', 'Bengaluru (Active Metro)', 'location_on'],
    ['customer.status.online', '', 'All Care Desks Online', 'sensors'],
    ['customer.emergency.badge', '', 'Emergency Helpline', 'emergency'],
    ['customer.emergency.helpline', '', '1800-AAYU-CARE', null],
    ['customer.emergency.desc', '', '24/7 Companion & Transit Desk', null],
    // Contact Page CMS Blocks (fully editable in CMS)
    ['contact.hero.eyebrow', '', 'WE ARE HERE FOR YOUR FAMILY • CARE COORDINATION HELPLINE', null],
    ['contact.hero.title', '', 'How can we help your family today?', null],
    ['contact.hero.subtitle', '', 'Whether you have an upcoming hospital consultation, need urgent next-day accompaniment, or wish to plan custom recurring elder care, our dedicated care counseling desk is ready to support you.', null],
    ['contact.live.wait_time', '', '38 seconds', null],
    ['contact.hubs.eyebrow', '', 'City Operations & Liaison', null],
    ['contact.hubs.title', '', 'Operational Hubs & Metro Presence', null],
    ['contact.hubs.subtitle', '', 'Stationed full-time companion coordinators in 30+ leading tertiary hospitals across key Indian metropolitan areas.', null],
    ['contact.emergency.title', '', 'Important Notice & Clinical Safety Scope', null],
    ['contact.emergency.body', '', 'AayuYukthi is not an emergency response service (EMS), ICU transit provider, or ambulance network. For acute, life-threatening medical emergencies, please immediately call 108 (Emergency Response) or 112, or proceed directly to the nearest hospital casualty emergency room.', null],
  ]) {
    await client.query(
      `INSERT INTO content_blocks (key, title_en, body_en, status, icon, updated_by) VALUES ($1,$2,$3,'published',$4,$5)
       ON CONFLICT (key) DO UPDATE SET title_en = EXCLUDED.title_en, body_en = EXCLUDED.body_en, icon = EXCLUDED.icon, status = 'published'`,
      [key, title, body, icon, userId],
    );
  }
  for (const [title, desc, label, order] of [
    ['Preparing for the Visit', 'Document pre-check, transport scheduling, and timing verification.', 'Prep', 0],
    ['Accompanied Travel & Arrival', 'Doorstep greeting, assisted boarding, and curbside hospital reception.', 'Travel', 1],
    ['Registration & Navigation', 'Paperwork assistance, tokens, and clinic check-ins — no confusing queues.', 'Hospital Nav', 2],
    ['Bedside & Waiting Support', 'Attentive companionship during consultations, tests, and prescriptions.', 'Care Support', 3],
    ['Safe Return Home', 'Prescription collection, discharge clearance, and safe drop-off.', 'Return', 4],
  ]) {
    await client.query(
      `INSERT INTO hero_slides (title_en, description_en, short_label_en, primary_cta_label_en, primary_cta_url,
          secondary_cta_label_en, secondary_cta_url, sort_order, is_active, created_by)
       SELECT $1,$2,$3,'Request Care','/request-care','Explore Services','/services',$4,true,$5
       WHERE NOT EXISTS (SELECT 1 FROM hero_slides WHERE title_en = $1)`,
      [title, desc, label, order, userId],
    );
  }
  await client.query(
    `UPDATE contact_settings SET phone='+919876543210', email='care@aayuyukthi.example',
       address_en='Vijayawada, Andhra Pradesh', hours_en='Mon–Sat, 9am–9pm', updated_by=$1 WHERE id=1`,
    [userId],
  );

  console.log('seed: ok — ops login ops@aayuyukthi.local / ChangeMe123! | Bhimavaram hospitals initialized');
} finally {
  await client.end();
}
